INFO 2019-01-19 18:52:15,415 basehttp 717 123145350438912 "GET / HTTP/1.1" 200 13021
WARNING 2019-01-19 18:52:16,154 log 717 123145350438912 Not Found: /favicon.ico
WARNING 2019-01-19 18:52:16,155 basehttp 717 123145350438912 "GET /favicon.ico HTTP/1.1" 404 17253
INFO 2019-01-19 18:52:23,665 basehttp 717 123145350438912 "GET /files/upload/ HTTP/1.1" 200 12818
INFO 2019-01-19 18:52:27,592 basehttp 717 123145350438912 "GET /shared_files/upload/ HTTP/1.1" 200 14611
INFO 2019-01-19 18:52:27,609 basehttp 717 123145350438912 "GET /static/js/upload_shared_file.js HTTP/1.1" 304 0
INFO 2019-01-19 18:52:31,157 basehttp 717 123145350438912 "GET /account/logout/ HTTP/1.1" 302 0
INFO 2019-01-19 18:52:31,193 basehttp 717 123145350438912 "GET / HTTP/1.1" 200 12750
INFO 2019-01-19 18:52:32,503 basehttp 717 123145350438912 "GET /shared_files/ HTTP/1.1" 302 0
INFO 2019-01-19 18:52:32,564 basehttp 717 123145350438912 "GET /account/login/?next=/shared_files/ HTTP/1.1" 200 12086
INFO 2019-01-19 18:53:09,110 basehttp 717 123145350438912 "GET / HTTP/1.1" 200 12700
INFO 2019-01-19 18:53:13,938 basehttp 717 123145350438912 "GET /accounts/register/ HTTP/1.1" 200 13842
INFO 2019-01-19 18:53:16,893 basehttp 717 123145350438912 "GET /account/login/ HTTP/1.1" 200 12086
INFO 2019-01-19 18:53:19,665 basehttp 717 123145350438912 "GET /account/two_factor/setup/ HTTP/1.1" 302 0
INFO 2019-01-19 18:53:19,717 basehttp 717 123145350438912 "GET /account/login/?next=/account/two_factor/setup/ HTTP/1.1" 200 12086
INFO 2019-01-19 18:53:29,125 basehttp 717 123145350438912 "GET /account/logout/ HTTP/1.1" 302 0
INFO 2019-01-19 18:53:29,169 basehttp 717 123145350438912 "GET / HTTP/1.1" 200 12700
INFO 2019-01-19 18:53:30,507 basehttp 717 123145350438912 "GET /account/login/ HTTP/1.1" 200 12086
INFO 2019-01-19 18:53:33,502 basehttp 717 123145350438912 "GET /files/upload/ HTTP/1.1" 302 0
INFO 2019-01-19 18:53:33,553 basehttp 717 123145350438912 "GET /account/login/?next=/files/upload/ HTTP/1.1" 200 12086
INFO 2019-01-19 20:04:54,039 basehttp 1204 123145445511168 "GET / HTTP/1.1" 200 12780
INFO 2019-01-19 20:04:55,673 basehttp 1204 123145445511168 "GET /accounts/password/reset/ HTTP/1.1" 200 12512
INFO 2019-01-19 20:05:11,974 basehttp 1204 123145445511168 "GET /account/login/ HTTP/1.1" 200 12086
INFO 2019-01-19 20:05:13,933 basehttp 1204 123145445511168 "GET / HTTP/1.1" 200 12780
INFO 2019-01-19 20:05:15,146 basehttp 1204 123145445511168 "GET /accounts/password/reset/ HTTP/1.1" 200 12512
INFO 2019-01-19 20:05:17,259 basehttp 1204 123145445511168 "GET /account/login/ HTTP/1.1" 200 12086
INFO 2019-01-19 20:05:19,035 basehttp 1204 123145445511168 "GET / HTTP/1.1" 200 12780
INFO 2019-01-19 20:05:25,569 basehttp 1204 123145445511168 "GET /accounts/password/reset/ HTTP/1.1" 200 12512
INFO 2019-01-19 20:05:26,552 basehttp 1204 123145445511168 "GET /account/login/ HTTP/1.1" 200 12086
INFO 2019-01-19 20:05:31,784 basehttp 1204 123145445511168 "GET / HTTP/1.1" 200 12780
INFO 2019-01-19 20:05:32,837 basehttp 1204 123145445511168 "GET /accounts/register/ HTTP/1.1" 200 13922
INFO 2019-01-19 20:05:33,678 basehttp 1204 123145445511168 "GET /shared_files/ HTTP/1.1" 302 0
INFO 2019-01-19 20:05:33,761 basehttp 1204 123145445511168 "GET /account/login/?next=/shared_files/ HTTP/1.1" 200 12086
INFO 2019-01-19 20:05:35,355 basehttp 1204 123145445511168 "GET / HTTP/1.1" 200 12780
INFO 2019-01-19 20:07:31,565 basehttp 1204 123145445511168 "GET / HTTP/1.1" 200 12780
INFO 2019-01-19 20:07:32,805 basehttp 1204 123145445511168 "GET / HTTP/1.1" 200 12780
INFO 2019-01-19 20:07:33,845 basehttp 1204 123145445511168 "GET /account/login/ HTTP/1.1" 200 12168
INFO 2019-01-19 20:07:36,526 basehttp 1204 123145445511168 "GET /accounts/password/reset/ HTTP/1.1" 200 12512
INFO 2019-01-19 20:07:39,018 basehttp 1204 123145445511168 "GET /account/login/ HTTP/1.1" 200 12168
INFO 2019-01-19 20:07:41,160 basehttp 1204 123145445511168 "GET /accounts/password/reset/ HTTP/1.1" 200 12512
INFO 2019-01-19 20:08:01,128 basehttp 1204 123145445511168 "GET /accounts/register/ HTTP/1.1" 200 13922
INFO 2019-01-19 20:08:01,757 basehttp 1204 123145445511168 "GET / HTTP/1.1" 200 12780
INFO 2019-01-19 20:08:03,560 basehttp 1204 123145445511168 "GET /accounts/password/reset/ HTTP/1.1" 200 12512
INFO 2019-01-19 20:08:07,061 basehttp 1204 123145445511168 "GET /account/login/ HTTP/1.1" 200 12168
INFO 2019-01-19 20:08:54,557 basehttp 1204 123145445511168 "GET / HTTP/1.1" 200 12780
INFO 2019-01-19 20:08:55,664 basehttp 1204 123145445511168 "GET /account/login/ HTTP/1.1" 200 12161
INFO 2019-01-19 20:09:30,133 basehttp 1204 123145445511168 "GET /accounts/password/reset/ HTTP/1.1" 200 12512
INFO 2019-01-19 20:10:03,544 basehttp 1204 123145445511168 "GET /accounts/password/reset/ HTTP/1.1" 200 12447
INFO 2019-01-19 20:10:05,862 basehttp 1204 123145445511168 "GET / HTTP/1.1" 200 12715
INFO 2019-01-19 20:10:07,686 basehttp 1204 123145445511168 "GET /accounts/register/ HTTP/1.1" 200 13857
INFO 2019-01-19 20:10:16,205 basehttp 1204 123145445511168 "GET /admin/ HTTP/1.1" 302 0
INFO 2019-01-19 20:10:16,217 basehttp 1204 123145445511168 "GET /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2019-01-19 20:10:16,273 basehttp 1204 123145445511168 "GET /account/login/?next=/admin/ HTTP/1.1" 200 12161
INFO 2019-01-19 20:10:24,961 basehttp 1204 123145445511168 "POST /account/login/?next=/admin/ HTTP/1.1" 200 12402
INFO 2019-01-19 20:10:28,411 basehttp 1204 123145445511168 "POST /account/login/?next=/admin/ HTTP/1.1" 200 11910
INFO 2019-01-19 20:10:45,750 basehttp 1204 123145445511168 "POST /account/login/?next=/admin/ HTTP/1.1" 200 12126
INFO 2019-01-19 20:11:01,749 basehttp 1204 123145445511168 "POST /account/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2019-01-19 20:11:01,906 basehttp 1204 123145445511168 "GET /admin/ HTTP/1.1" 200 11053
INFO 2019-01-19 20:11:04,380 basehttp 1204 123145445511168 "GET / HTTP/1.1" 200 12966
INFO 2019-01-19 20:11:07,914 basehttp 1204 123145445511168 "GET /account/sessions/ HTTP/1.1" 200 13251
INFO 2019-01-19 20:11:14,865 basehttp 1204 123145445511168 "GET / HTTP/1.1" 200 12966
INFO 2019-01-19 20:11:21,087 basehttp 1204 123145445511168 "GET /account/sessions/ HTTP/1.1" 200 13251
INFO 2019-01-19 20:12:51,337 basehttp 1204 123145445511168 "GET / HTTP/1.1" 200 12966
INFO 2019-01-19 20:12:54,248 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 200 13258
INFO 2019-01-19 20:16:41,828 basehttp 1204 123145445511168 "GET /account/two_factor/backup/tokens/ HTTP/1.1" 200 11412
INFO 2019-01-19 20:16:44,601 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 200 13258
INFO 2019-01-19 20:19:13,221 basehttp 1204 123145445511168 "GET /account/two_factor/backup/tokens/ HTTP/1.1" 200 11413
INFO 2019-01-19 20:19:14,607 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 200 13258
ERROR 2019-01-19 20:20:06,059 log 1204 123145445511168 Internal Server Error: /account/two_factor/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'else'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 26: 'else', expected 'endblock'. Did you forget to register or load this tag?
ERROR 2019-01-19 20:20:06,089 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 500 167785
ERROR 2019-01-19 20:20:32,076 log 1204 123145445511168 Internal Server Error: /account/two_factor/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 12: 'endif', expected 'endblock'. Did you forget to register or load this tag?
ERROR 2019-01-19 20:20:32,110 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 500 167728
ERROR 2019-01-19 20:20:45,517 log 1204 123145445511168 Internal Server Error: /account/two_factor/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'else'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 48: 'else', expected 'endblock'. Did you forget to register or load this tag?
ERROR 2019-01-19 20:20:45,551 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 500 170737
ERROR 2019-01-19 20:20:49,777 log 1204 123145445511168 Internal Server Error: /account/two_factor/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'else'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 48: 'else', expected 'endblock'. Did you forget to register or load this tag?
ERROR 2019-01-19 20:20:49,806 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 500 170602
INFO 2019-01-19 20:21:01,883 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 200 13258
ERROR 2019-01-19 20:22:33,880 log 1204 123145445511168 Internal Server Error: /account/two_factor/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'default_device=0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 7: 'default_device=0', expected 'endblock'. Did you forget to register or load this tag?
ERROR 2019-01-19 20:22:33,916 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 500 172895
ERROR 2019-01-19 20:23:24,047 log 1204 123145445511168 Internal Server Error: /account/two_factor/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loader_tags.py", line 205, in do_block
    raise TemplateSyntaxError("'%s' tag with name '%s' appears more than once" % (bits[0], block_name))
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'content' appears more than once
ERROR 2019-01-19 20:23:24,077 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 500 172300
ERROR 2019-01-19 20:23:43,189 log 1204 123145445511168 Internal Server Error: /account/two_factor/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'default_device=0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 8: 'default_device=0', expected 'endblock'. Did you forget to register or load this tag?
ERROR 2019-01-19 20:23:43,220 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 500 186544
INFO 2019-01-19 20:24:09,916 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 200 13259
INFO 2019-01-19 20:24:53,882 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 200 13185
INFO 2019-01-19 20:24:59,043 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 200 13185
INFO 2019-01-19 20:25:08,177 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 200 13258
INFO 2019-01-19 20:25:43,496 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 200 13180
INFO 2019-01-19 20:26:02,849 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 200 12861
INFO 2019-01-19 20:26:14,607 basehttp 1204 123145445511168 "GET /account/two_factor/backup/tokens/ HTTP/1.1" 200 11411
INFO 2019-01-19 20:26:16,449 basehttp 1204 123145445511168 "POST /account/two_factor/backup/tokens/ HTTP/1.1" 302 0
INFO 2019-01-19 20:26:16,552 basehttp 1204 123145445511168 "GET /account/two_factor/backup/tokens/ HTTP/1.1" 200 11779
INFO 2019-01-19 20:26:20,500 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 200 12862
INFO 2019-01-19 20:26:36,298 basehttp 1204 123145445511168 "GET /account/two_factor/backup/tokens/ HTTP/1.1" 200 11779
INFO 2019-01-19 20:26:44,216 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 200 12862
INFO 2019-01-19 20:26:47,850 basehttp 1204 123145445511168 "GET /account/logout/ HTTP/1.1" 302 0
INFO 2019-01-19 20:26:47,892 basehttp 1204 123145445511168 "GET / HTTP/1.1" 200 12715
INFO 2019-01-19 20:26:51,023 basehttp 1204 123145445511168 "GET /accounts/register/ HTTP/1.1" 200 13857
INFO 2019-01-19 20:27:11,487 basehttp 1204 123145445511168 "POST /accounts/register/ HTTP/1.1" 302 0
INFO 2019-01-19 20:27:11,523 basehttp 1204 123145445511168 "GET /accounts/register/complete/ HTTP/1.1" 200 12049
INFO 2019-01-19 20:27:28,047 basehttp 1204 123145445511168 "GET /accounts/activate/01ed9b538d634c260a1daebe6d6e6f4f5eb53c38/ HTTP/1.1" 302 0
INFO 2019-01-19 20:27:28,085 basehttp 1204 123145445511168 "GET /accounts/activate/complete/ HTTP/1.1" 200 12108
INFO 2019-01-19 20:27:39,719 basehttp 1204 123145445511168 "GET /accounts/approve/2/ HTTP/1.1" 302 0
INFO 2019-01-19 20:27:39,767 basehttp 1204 123145445511168 "GET /account/login/?next=/accounts/approve/2/ HTTP/1.1" 200 12161
INFO 2019-01-19 20:27:48,365 basehttp 1204 123145445511168 "POST /account/login/?next=/accounts/approve/2/ HTTP/1.1" 200 12140
INFO 2019-01-19 20:28:13,573 basehttp 1204 123145445511168 "POST /account/login/?next=/accounts/approve/2/ HTTP/1.1" 302 0
INFO 2019-01-19 20:28:15,487 basehttp 1204 123145445511168 "GET /accounts/approve/2/ HTTP/1.1" 302 0
INFO 2019-01-19 20:28:15,547 basehttp 1204 123145445511168 "GET /accounts/approve/complete/ HTTP/1.1" 200 12274
INFO 2019-01-19 20:28:24,954 basehttp 1204 123145445511168 "GET /account/login/ HTTP/1.1" 200 12159
INFO 2019-01-19 20:28:32,634 basehttp 1204 123145445511168 "POST /account/login/ HTTP/1.1" 302 0
INFO 2019-01-19 20:28:32,764 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 200 12478
INFO 2019-01-19 20:28:34,126 basehttp 1204 123145445511168 "GET /account/two_factor/setup/ HTTP/1.1" 200 11536
INFO 2019-01-19 20:28:35,409 basehttp 1204 123145445511168 "POST /account/two_factor/setup/ HTTP/1.1" 200 12577
INFO 2019-01-19 20:28:42,172 basehttp 1204 123145445511168 "POST /account/two_factor/setup/ HTTP/1.1" 200 12068
INFO 2019-01-19 20:28:42,259 basehttp 1204 123145445511168 "GET /account/two_factor/qrcode/ HTTP/1.1" 200 28941
INFO 2019-01-19 20:28:59,234 basehttp 1204 123145445511168 "POST /account/two_factor/setup/ HTTP/1.1" 302 0
INFO 2019-01-19 20:28:59,306 basehttp 1204 123145445511168 "GET /account/two_factor/setup/complete/ HTTP/1.1" 200 11209
INFO 2019-01-19 20:29:04,848 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 200 12858
INFO 2019-01-19 20:29:21,524 basehttp 1204 123145445511168 "GET /account/two_factor/setup/complete/ HTTP/1.1" 200 11209
INFO 2019-01-19 20:31:01,610 basehttp 1204 123145445511168 "GET /account/two_factor/setup/complete/ HTTP/1.1" 200 10940
INFO 2019-01-19 20:31:05,492 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 200 12858
INFO 2019-01-19 20:31:36,673 basehttp 1204 123145445511168 "GET /account/two_factor/setup/complete/ HTTP/1.1" 200 10940
INFO 2019-01-19 20:32:44,001 basehttp 1204 123145445511168 "GET /admin/ HTTP/1.1" 302 0
INFO 2019-01-19 20:32:44,016 basehttp 1204 123145445511168 "GET /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2019-01-19 20:32:44,109 basehttp 1204 123145445511168 "GET /account/login/?next=/admin/ HTTP/1.1" 200 12159
INFO 2019-01-19 20:32:48,288 basehttp 1204 123145445511168 "POST /account/login/?next=/admin/ HTTP/1.1" 200 12404
INFO 2019-01-19 20:32:53,282 basehttp 1204 123145445511168 "POST /account/login/?next=/admin/ HTTP/1.1" 200 12404
INFO 2019-01-19 20:33:00,420 basehttp 1204 123145445511168 "POST /account/login/?next=/admin/ HTTP/1.1" 200 12140
INFO 2019-01-19 20:33:19,524 basehttp 1204 123145445511168 "POST /account/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2019-01-19 20:33:19,606 basehttp 1204 123145445511168 "GET /admin/ HTTP/1.1" 200 11051
INFO 2019-01-19 20:33:34,954 basehttp 1204 123145445511168 "GET /static/debug_toolbar/img/djdt_vertical.png HTTP/1.1" 200 882
INFO 2019-01-19 20:33:38,114 basehttp 1204 123145445511168 "GET /admin/password_change/ HTTP/1.1" 200 12973
INFO 2019-01-19 20:33:50,528 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 200 12862
INFO 2019-01-19 20:35:05,195 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 200 12862
INFO 2019-01-19 20:35:09,797 basehttp 1204 123145445511168 "GET /account/logout/ HTTP/1.1" 302 0
INFO 2019-01-19 20:35:09,836 basehttp 1204 123145445511168 "GET / HTTP/1.1" 200 12715
INFO 2019-01-19 20:35:11,789 basehttp 1204 123145445511168 "GET /account/login/ HTTP/1.1" 200 12161
INFO 2019-01-19 20:35:13,055 basehttp 1204 123145445511168 "GET /accounts/password/reset/ HTTP/1.1" 200 12447
INFO 2019-01-19 20:35:18,492 basehttp 1204 123145445511168 "POST /accounts/password/reset/ HTTP/1.1" 302 0
INFO 2019-01-19 20:35:18,530 basehttp 1204 123145445511168 "GET /accounts/password/reset/done/ HTTP/1.1" 200 12123
INFO 2019-01-19 20:35:53,318 basehttp 1204 123145445511168 "GET /accounts/password/reset/confirm/NA/534-a1d2ba4489a3521493c9/ HTTP/1.1" 302 0
INFO 2019-01-19 20:35:53,405 basehttp 1204 123145445511168 "GET /accounts/password/reset/confirm/NA/set-password/ HTTP/1.1" 200 12564
INFO 2019-01-19 20:36:01,628 basehttp 1204 123145445511168 "POST /accounts/password/reset/confirm/NA/set-password/ HTTP/1.1" 302 0
INFO 2019-01-19 20:36:01,665 basehttp 1204 123145445511168 "GET /accounts/password/reset/complete/ HTTP/1.1" 200 12093
INFO 2019-01-19 20:36:05,221 basehttp 1204 123145445511168 "GET /account/login/ HTTP/1.1" 200 12161
INFO 2019-01-19 20:36:18,507 basehttp 1204 123145445511168 "POST /account/login/ HTTP/1.1" 200 11910
INFO 2019-01-19 20:36:29,292 basehttp 1204 123145445511168 "POST /account/login/ HTTP/1.1" 302 0
INFO 2019-01-19 20:36:29,448 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 200 12860
INFO 2019-01-19 20:36:37,473 basehttp 1204 123145445511168 "GET /account/two_factor/disable/ HTTP/1.1" 200 11256
INFO 2019-01-19 20:36:40,125 basehttp 1204 123145445511168 "POST /account/two_factor/disable/ HTTP/1.1" 302 0
INFO 2019-01-19 20:36:40,271 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 200 12478
INFO 2019-01-19 20:36:46,881 basehttp 1204 123145445511168 "GET /files/list/ HTTP/1.1" 302 0
INFO 2019-01-19 20:36:46,950 basehttp 1204 123145445511168 "GET /account/login/?next=/files/list/ HTTP/1.1" 200 12157
INFO 2019-01-19 20:36:54,878 basehttp 1204 123145445511168 "POST /account/login/?next=/files/list/ HTTP/1.1" 302 0
INFO 2019-01-19 20:36:54,911 basehttp 1204 123145445511168 "GET /files/list/ HTTP/1.1" 302 0
INFO 2019-01-19 20:36:54,977 basehttp 1204 123145445511168 "GET /account/login/?next=/files/list/ HTTP/1.1" 200 12157
INFO 2019-01-19 20:37:00,758 basehttp 1204 123145445511168 "POST /account/login/?next=/files/list/ HTTP/1.1" 302 0
INFO 2019-01-19 20:37:00,786 basehttp 1204 123145445511168 "GET /files/list/ HTTP/1.1" 302 0
INFO 2019-01-19 20:37:00,852 basehttp 1204 123145445511168 "GET /account/login/?next=/files/list/ HTTP/1.1" 200 12157
INFO 2019-01-19 20:37:03,393 basehttp 1204 123145445511168 "GET / HTTP/1.1" 200 12917
INFO 2019-01-19 20:37:04,894 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 200 12478
INFO 2019-01-19 20:37:06,344 basehttp 1204 123145445511168 "GET /account/two_factor/setup/ HTTP/1.1" 200 11536
INFO 2019-01-19 20:37:08,845 basehttp 1204 123145445511168 "POST /account/two_factor/setup/ HTTP/1.1" 200 12577
INFO 2019-01-19 20:39:36,552 basehttp 1204 123145445511168 "POST /account/two_factor/setup/ HTTP/1.1" 200 11534
INFO 2019-01-19 20:39:40,397 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 200 12478
INFO 2019-01-19 20:39:42,218 basehttp 1204 123145445511168 "GET /account/two_factor/setup/ HTTP/1.1" 200 11536
INFO 2019-01-19 20:39:43,345 basehttp 1204 123145445511168 "POST /account/two_factor/setup/ HTTP/1.1" 200 12577
INFO 2019-01-19 20:45:22,194 basehttp 1204 123145445511168 "GET /accounts/approve/2/ HTTP/1.1" 302 0
INFO 2019-01-19 20:45:22,277 basehttp 1204 123145445511168 "GET /account/login/?next=/accounts/approve/2/ HTTP/1.1" 200 12157
INFO 2019-01-19 20:45:44,685 basehttp 1204 123145445511168 "GET /account/login/ HTTP/1.1" 200 12157
INFO 2019-01-19 20:47:56,616 basehttp 1204 123145445511168 "GET / HTTP/1.1" 200 12917
INFO 2019-01-19 20:47:58,160 basehttp 1204 123145445511168 "GET /files/list/ HTTP/1.1" 302 0
INFO 2019-01-19 20:47:58,222 basehttp 1204 123145445511168 "GET /account/login/?next=/files/list/ HTTP/1.1" 200 12157
INFO 2019-01-19 20:48:02,471 basehttp 1204 123145445511168 "GET / HTTP/1.1" 200 12917
INFO 2019-01-19 20:48:06,841 basehttp 1204 123145445511168 "GET / HTTP/1.1" 200 12917
INFO 2019-01-19 20:48:09,299 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 200 12478
INFO 2019-01-19 20:48:11,068 basehttp 1204 123145445511168 "GET /account/two_factor/setup/ HTTP/1.1" 200 11536
INFO 2019-01-19 20:48:12,202 basehttp 1204 123145445511168 "POST /account/two_factor/setup/ HTTP/1.1" 200 12577
INFO 2019-01-19 20:48:13,395 basehttp 1204 123145445511168 "POST /account/two_factor/setup/ HTTP/1.1" 200 12068
INFO 2019-01-19 20:48:13,462 basehttp 1204 123145445511168 "GET /account/two_factor/qrcode/ HTTP/1.1" 200 28317
INFO 2019-01-19 20:48:37,386 basehttp 1204 123145445511168 "POST /account/two_factor/setup/ HTTP/1.1" 302 0
INFO 2019-01-19 20:48:37,449 basehttp 1204 123145445511168 "GET /account/two_factor/setup/complete/ HTTP/1.1" 200 10940
INFO 2019-01-19 20:48:39,960 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 200 12858
INFO 2019-01-19 20:48:44,052 basehttp 1204 123145445511168 "GET /files/list/ HTTP/1.1" 302 0
INFO 2019-01-19 20:48:44,125 basehttp 1204 123145445511168 "GET /encryptionkey/ HTTP/1.1" 200 13224
INFO 2019-01-19 20:48:45,764 basehttp 1204 123145445511168 "GET /shared_files/ HTTP/1.1" 200 12664
INFO 2019-01-19 20:48:46,763 basehttp 1204 123145445511168 "GET /accounts/register/ HTTP/1.1" 302 0
INFO 2019-01-19 20:48:46,875 basehttp 1204 123145445511168 "GET /account/two_factor/ HTTP/1.1" 200 12858
INFO 2019-01-19 21:11:10,761 basehttp 1806 123145426944000 "GET / HTTP/1.1" 200 12967
INFO 2019-01-19 21:11:13,280 basehttp 1806 123145426944000 "GET /account/sessions/ HTTP/1.1" 200 13251
INFO 2019-01-19 21:11:28,402 basehttp 1806 123145426944000 "GET /account/sessions/ HTTP/1.1" 200 13067
